### ISSUE TITLE
修改词库文件后闪退无法打开

### ISSUE THREAD

**Issue by bosconb** [KyleBing/WubiBuddy#2]
首次打开正常，然后想试试一定数量自定义词的效果，于是直接用文本编辑器（coteditor）打开wubi86_jidian_addition.dict文件，添加了自己过去的几百行词组，打开即闪退。

之后一直无法打开WubiBuddy，删除程序和wubi86_jidian_addition.dict用原始文覆盖了一遍。再次打开时依然闪退，始终无法打开主界面（但wubi86_jidian_addition.dict新添加的词已经生效）。

请教该如何初始化程序？

**Comment by KyleBing** [comment]
😂果不其然，bug 还是很多的，现在写的比较死板，只是刚刚实现了基础的功能，里面也没有实现足够的容错机制，所以很容易死，哈哈。

是这样的，你里面必须要有一行 `...` 三个点的行，像这样：
```yaml
...
```

程序里面是以这个为头部和内容的分隔点的，其它不影响。
你应该是把这行给去了可能，加上就可以了应该。

**Comment by bosconb** [comment]
> 😂果不其然，bug 还是很多的，现在写的比较死板，只是刚刚实现了基础的功能，里面也没有实现足够的容错机制，所以很容易死，哈哈。
> 
> 是这样的，你里面必须要有一行 `...` 三个点的行，像这样：
> 
> ```yaml
> ...
> ```
> 
> 程序里面是以这个为头部和内容的分隔点的，其它不影响。
> 你应该是把这行给去了可能，加上就可以了应该。

谢谢及时答复，好像是格式的问题，我又用官方的wubi86_jidian_addition.dict重新覆盖了一遍，程序能够打开了，哈哈

**Comment by KyleBing** [comment]
OK
