### ISSUE TITLE
文件损坏

### ISSUE THREAD

**Issue by martinmts** [KyleBing/WubiBuddy#3]
你好，安装完成后，无法使用。
不知道哪里出错了。

![image](https://user-images.githubusercontent.com/32575091/92043261-bd25fb80-ed49-11ea-984b-54160091cdc5.png)

**Comment by KyleBing** [comment]
嗯，目前是有这个问题，是关于软件签名的。百度 mac 软件签名问题，这个后续完善。

**Comment by mangobuaa** [comment]
现在最小化用户配置文件，有需要的就往里加，希望有了码表助手会更方便。多谢作者

**Comment by martinmts** [comment]
现在用 Keyboard Maestro 完美解决了这个需求。

1. 先把所有单字和其五笔码提取出来，作为单字的词库，保存在某处。
2. 选中任何要添加到词库中的字词。按下快捷键。 Keyboard Maestro 根据选中内容的长度，如果是二个字，就在前面的词库中找各个词的前两个五笔码，如果是三个字，就找前两个字的首码和第三个字的前两个码。如果是四或以上个字，就取前三字和最后一字的首码。
3. Keyboard Maestro 自动将获得的结果其作为新词的五笔码，并添加到 Rime 的用户字库文档中。

以上第一步只是一次性的。我把单字词库放在 Named Clipboard （下图 wubidanzi）中。
在 Keyboard Maestro 中设定好如下图所示 Macro 之后，操作步骤就很简单了。碰到想要添加的新词，1. 选中它，2. 按下快捷键，3. 再按下 “Return”。新词就会自动被添加到用户词库文档中，并且自动进行重新布署。

![image](https://user-images.githubusercontent.com/32575091/92943572-f08b1900-f420-11ea-855e-4b28973e3c5a.png)

**Comment by KyleBing** [comment]
如果提示无法打开，文件损坏什么的，将 app 移到应用程序 `Applications` 文件夹后，打开终端 `Terminal`，这样操作：
```bash
sudo xattr -rd com.apple.quarantine /Applications/码表助手.app/
```
